### ISSUE TITLE
I wonder why this is not part of standard Elixir?

### ISSUE THREAD

**Issue by samphilipd** [folz/math#6]
We have Elixir wrappers for other Erlang built-ins like List (:lists), Map (:maps) etc. I wonder why this library isn't in the Elixir standard distribution?

**Comment by folz** [comment]
I asked about this on elixir-lang-core[0] -- Jose's response was that he didn't want simple defdelegate wrappers around erlang modules in the standard library.

The deleted message at the bottom of the thread was me asking about it approx one year later (after adding elixir-native functions beyond what erlang :math offered). I didn't get a reason for its deletion, but would guess based on other tweets/emails I've seen from him that he prefers to have libraries in hex, not in stdlib.

I'm fine with this being third-party; for me, it was mostly an exercise in publishing a package and erlang interop.

[0]: https://groups.google.com/forum/#!topic/elixir-lang-core/5qxH1apXbzQ
